### PR TITLE
Vagrant setup fixes

### PR DESCRIPTION
**Pull request by brittainhard**

### CODE REVIEW

**Comment by ahmadia** [comment]
Thanks @brittainhard, could you explain a little more what "crawl settings" was and why you removed it?  The saltfile copy move looks correct.

**Comment by brittainhard** [comment]
Crawl settings was a set of settings that was in place for the old non-celery crawlers. My assumption was that they were there to provide crawl supervisor with the settings it needed, since it didn't actually run within django. That's why you see `from django.conf import settings`. That line will set up your environment to be able access the django views and models, and without it you can't make any changes.

I just felt that it was redundant, and it was causing a couple issues for setting up deployment and development settings files, namely the ability to keep the profiles and configs path separate from the directories where the crawl data is dumped.

**Comment by brittainhard** [comment]
Not entirely sure how good of an idea that was actually, I think it might be causing the tests to fail. Rough day :/

**Comment by brittainhard** [comment]
Merging if no comment.

**Pull request merged**
