### PR TITLE
Small v0.4 fixes

### PR DESCRIPTION
**Pull request by ahmadia**
* close https://github.com/memex-explorer/memex-explorer/issues/730
* close https://github.com/memex-explorer/memex-explorer/issues/734

### CODE REVIEW

**Comment by ahmadia** [comment]
more coming down the pipe :)

**Comment by ahmadia** [comment]
* close https://github.com/memex-explorer/memex-explorer/issues/731

**Comment by ahmadia** [comment]
Also moved the Django logs over from `memex/logs` so everything lives in `resources/logs`.

**Comment by ahmadia** [comment]
* close https://github.com/memex-explorer/memex-explorer/issues/728

**Comment by ahmadia** [comment]
These are ready for review.

**Comment by ahmadia** [comment]
* close https://github.com/memex-explorer/memex-explorer/issues/727

**Comment by ahmadia** [comment]
@brittainhard - suggestions incorporated.

**Comment by ahmadia** [comment]
Okay, I think this is ready for final review/merge.

**Comment by brittainhard** [comment]
+1 on merging

**Pull request merged**
