### PR TITLE
Amfarrell/docker link settings

### PR DESCRIPTION
**Pull request by amfarrell**
@brittainhard would you be able to CR this when you get the chance?

@ahmadia,  we want Log.io to live /logio/, correct?

### CODE REVIEW

**Comment by amfarrell** [comment]
This is to solve issue #597

**Comment by amfarrell** [comment]
HTTP_ORIGIN is apparently not present within request.META on Travis CI. This means it is not a reliable source of the base of the url. I'll need to fix this.

**Comment by ahmadia** [comment]
@amfarrell - we should be using the same versions of code on Travis CI.  Perhaps double-check that it's installing the same version of request/requests?

**Comment by amfarrell** [comment]
@brittainhard can you take a look at the travis CI error here. I can't figure out why this query would be failing.

**Comment by brittainhard** [comment]
@amfarrell if deleting a crawl works then I would just set the test to xfail for now and make an issue.

**Pull request merged**
