### PR TITLE
[WIP] Bhard/data upload

### PR DESCRIPTION
**Pull request by brittainhard**

### CODE REVIEW

**Comment by ahmadia** [comment]
Sweet!  I'll review as soon as I'm back from lunch.

**Comment by brittainhard** [comment]
Still a work in progress @ahmadia. Almost done with the unzip function.

**Comment by brittainhard** [comment]
@ahmadia this is ready to review. The only things left are to add testing and fix currently broken tests.

**Comment by ahmadia** [comment]
Visual inspection all seems reasonable.

**Comment by ahmadia** [comment]
While we were reviewing this we identified a problem with passing file objects to Celery through Django.  We're going to use a file name instead, since there's no reason to pass an open file handle to the Celery task manager.  cc: @amfarrell @brittainhard

**Comment by ahmadia** [comment]
I'm going to try and figure out what's broken in the tests.

**Comment by ahmadia** [comment]
@brittainhard and I decided to set the failing tests as expected failures for now, and to raise an issue to go back and look at them later.  This completes the "upload" step.  We now need to implement the tika pipeline and the visualization with kibana.

**Pull request merged**
