### PR TITLE
Amfarrell/create ec2

### PR DESCRIPTION
**Pull request by amfarrell**
implements pushbutton deploy onto ec2

### CODE REVIEW

**Comment by ahmadia** [comment]
Sweet. Do you want to merge or wait until I can test/review this weekend?

**Comment by amfarrell** [comment]
I would prefer to merge this now so that I can start branching based off of it.

**Comment by ahmadia** [comment]
Alright let's do it. I'll take a look at the PR this weekend.

**Comment by ahmadia** [comment]
To be clear, go ahead and merge now.

**Pull request merged**
