### PR TITLE
ahmadia/tag 0.4

### PR DESCRIPTION
**Pull request by ahmadia**

### CODE REVIEW

**Comment by ahmadia** [comment]
This is ready to merge I think.

**Comment by ahmadia** [comment]
Oops, I think I forgot to bump the documents version.

**Comment by ahmadia** [comment]
Fixed.  @brittainhard - this is ready for review, but I think we're ready to cut the 0.4 release.

**Comment by ahmadia** [comment]
@brittainhard - any thoughts?

**Comment by brittainhard** [comment]
Looks fine to me. I don't have time to test it unfortunately.

**Pull request merged**
