### PR TITLE
log.io work 

### PR DESCRIPTION
**Pull request by ahmadia**

### CODE REVIEW

**Comment by ahmadia** [comment]
I'll merge this when I've got the log.io harvesters/servers going.

**Comment by lewismc** [comment]
Ack, tried to build from master today and seems to hang on vagrant up stage.
Which branch is 'stable'?


On Tuesday, May 26, 2015, Aron Ahmadia <notifications@github.com> wrote:

> I'll merge this when I've got the log.io harvesters/servers going.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/memex-explorer/memex-explorer/pull/539#issuecomment-105711292>
> .
>


-- 
*Lewis*

**Comment by ahmadia** [comment]
"stable"?

Try:

```
git fetch
git checkout origin/master
vagrant reload
vagrant provision
```

Open an issue if anything's broken, master should be stable-ish.

**Comment by lewismc** [comment]
Ok will try tomorrow I'm heading home

On Tuesday, May 26, 2015, Aron Ahmadia <notifications@github.com> wrote:

> "stable"?
>
> Try:
>
> git fetch
> git checkout origin/master
> vagrant reload
> vagrant provision
>
> Open an issue if anything's broken, master should be stable-ish.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/memex-explorer/memex-explorer/pull/539#issuecomment-105713595>
> .
>


-- 
*Lewis*

**Comment by ahmadia** [comment]
Great!  Expect significant fixes this evening.  I'm trying to stabilize everything for tomorrow AM.

**Comment by ahmadia** [comment]
This is ready for testing.

**Comment by ahmadia** [comment]
Who's that lone cowboy merging into master without review?

**Pull request merged**
