### PR TITLE
Update Tika into PIP section.

### PR DESCRIPTION
**Pull request by chrismattmann**

### CODE REVIEW

**Comment by ahmadia** [comment]
@chrismattmann - are you using Git from the command line?  You can simply push your branch again and it will update the PR.

**Comment by chrismattmann** [comment]
yeah I'm using hub.github.com 

I pushed the branch, odd wondering why it didn't update the PR? Anyways if someone merges this just mention closing the previous PR and it will close.

**Comment by ahmadia** [comment]
@chrismattmann - #482 uses a branch from your fork, this PR uses a branch pushed directly to this repository.  Both development models are fine (I prefer to work with branches within the local repository like this one).

**Comment by ahmadia** [comment]
It's not a big deal, was just pointing out an FYI.  I'll close the other PR now.

**Comment by chrismattmann** [comment]
Oh I think I set the wrong upstream thanks for the catch and merge!

**Comment by chrismattmann** [comment]
Hmmm what's the error now

**Comment by brittainhard** [comment]
@chrismattmann does your editor uses tab characters instead of spaces? it looks like it didnt like the "\t" character. just need to convert tabs to spaces on the environment.yml file

**Comment by ahmadia** [comment]
I've updated the branch, corrected the pip syntax, and tested the install locally.  This should all work correctly now.

**Comment by ahmadia** [comment]
Oooph, more fixes needed.

**Comment by ahmadia** [comment]
@chrismattmann - It looks like tika Python doesn't install correctly from pip.  In particular, it seems to be missing an __init__.py file...

**Comment by ahmadia** [comment]
Nope, just not what I was expecting in the __init__.py file (I *hate* namespace packages and setuptools with the fiery burning passion of a 1,000 suns).  Anyway, I think it should be working now.

**Comment by chrismattmann** [comment]
awesome thanks @ahmadia for the fix! haha I come from the Plone world, at least I didn't use buildout ;)

**Pull request merged**
