### PR TITLE
Celery Crawlers

### LINKED ISSUE #439: Allow user to specify how many rounds nutch will crawl.
Right now it runs indefinitely. This is not necessarily good, and the user has no idea about the progress of the crawl. We should allow the user to specify how many rounds they want, and/or allow them to see how many rounds have been run, and manually restart a round.

### PR DESCRIPTION
**Pull request by brittainhard**
closes #439

### CODE REVIEW

**Comment by ahmadia** [comment]
Looks straightforward.

**Comment by brittainhard** [comment]
@ahmadia still WIP :)

**Comment by brittainhard** [comment]
Things left to do:
- [] Add force-stop button
- [] Make nutch stop after the round is done if stop button is pressed

**Comment by brittainhard** [comment]
merging if no comment

**Pull request merged**
