### PR TITLE
Handle new statuses.

### LINKED ISSUE #762: on/off statuses still occasionally break
Three things:

* First, the JS here is non-critical.  If it sees a state it doesn't recognize, it should just log a warning to the console.  This keeps the rest of the JS on the page from breaking (and hopefully, we'll be in a state we recognize soon)

* It should then be pretty easy to identify what's the bad state, since we'll get a nice logged message to the console.

* Finally, at some point we should refactor the on/off states.  This isn't something to deal with in this issue, but I'd like to create another issue to handle this and this is my reminder to discuss this :)

### PR DESCRIPTION
**Pull request by brittainhard**
Closes #762

### CODE REVIEW

**Comment by brittainhard** [comment]
@ahmadia wanna review this?

**Comment by ahmadia** [comment]
Thanks Brittain.  This doesn't close #762 until the on/off JS code is updated with the try/except logic and the ability to log bad statuses to the JS console (instead of crashing the JS in the browser).

**Comment by brittainhard** [comment]
Oh. I can add that quickly. I had it in for testing purposes, but I may as well add it back in.

**Comment by brittainhard** [comment]
Put this on the wrong branch. Closing.

**Comment by ahmadia** [comment]
Huh?

**Comment by brittainhard** [comment]
This branch was called bhard/docs_migrations, and was not the statuses branch. I dont think it made a difference, but I wanted to keep the names consistent.

**Pull request closed without merging**
