### PR TITLE
Better debugging of celery / shell=True for path

### PR DESCRIPTION
**Pull request by ahmadia**
@brittainhard - please review

This is my new error after this gets merged:

screen

### CODE REVIEW

**Comment by ahmadia** [comment]
This fixes https://github.com/memex-explorer/memex-explorer/issues/528

**Comment by brittainhard** [comment]
Are you running log.io?

**Comment by ahmadia** [comment]
Is log.io merged into master?

**Comment by ahmadia** [comment]
Yes, yes it is...

**Comment by ahmadia** [comment]
I have a vague recollection of telling you to do that.  Okay, let me see if I can retrace steps from Friday.

**Comment by brittainhard** [comment]
yeah i just need to add a conditional that only shows that box if we are running deployment settings, it's already on my branch

**Comment by ahmadia** [comment]
Does the rest of it look okay?  If so, LGTM.

**Comment by brittainhard** [comment]
So what does shell=True do, output stdout through celery?

**Comment by ahmadia** [comment]
@brittainhard - see http://stackoverflow.com/questions/3172470/actual-meaning-of-shell-true-in-subprocess for some commentary.  The reason I'm doing this is it's the simplest way to get the path to nutch/the conda environment, which is currently only stored in a local bashrc settings file, instead of a configuration file like the one @amfarrell is working on.

**Comment by brittainhard** [comment]
Ok, sounds fine to me.

**Pull request merged**
