### PR TITLE
Update to latest version of Docker in Salt

### PR DESCRIPTION
**Pull request by ahmadia**
@brittainhard - can you test this when you get a chance?  Just a warning but you will probably need to start with a fresh vagrant box.

### CODE REVIEW

**Comment by ahmadia** [comment]
Actually, hold on.  I think there's a Docker configuration file that needs to be set on Ubuntu.

**Comment by ahmadia** [comment]
Just a warning but I need to merge this PR very soon for TAD integration, so if it goes unreviewed I'll merge it myself at end of day today.

This upgrades to the latest version of Docker.  Should make things much easier since the new version of Docker has nice commands for debugging and interacting with containers.

**Comment by brittainhard** [comment]
Yeah give me about 25 minutes to get the box up and running.

**Comment by brittainhard** [comment]
I tested this out and had no obvious issues.

**Comment by ahmadia** [comment]
Thanks!  I need to review yours but feel free to merge both now.

**Pull request merged**
