### PR TITLE
[WIP] Add Index

### LINKED ISSUE #459: Make setting for disabling docker container creation.
Needs to prevent creation based on whether the dev settings or the deploy settings are being used. Can just wrap an if clause around the container creation command.

```
if settings.DEPLOYMENT:
    post_save()
```

### LINKED ISSUE #460: Create Index View
Need simple form view for creating an index.

### LINKED ISSUE #461: Index Table
Need a table for tracking the names of indices and the files associated with them.

### PR DESCRIPTION
**Pull request by brittainhard**
closes #460 
closes #461 
closes #459

### CODE REVIEW

**Comment by ahmadia** [comment]
Cool.  Should I take a look at this?

**Comment by brittainhard** [comment]
@ahmadia as soon as I get it passing the build. There are some more things to add though, it will be done tomorrow.

**Comment by ahmadia** [comment]
okay, just flag me

**Comment by brittainhard** [comment]
@ahmadia I expect to have this done before about 3 tomorrow. You can test out this branch if you need to. Make sure you create the new settings file. This will only work if you copy the dev settings file (see README). Right now it just unzips the files, and the index creation task has been disabled. @amfarrell and I probably have to work on making this work with a local environment that has tika, ES, and kibana.

**Comment by brittainhard** [comment]
closes #465

**Comment by brittainhard** [comment]
Have to close this and make a new PR to be merged off master after dockerize has been merged.

**Pull request closed without merging**
