### PR TITLE
Crawljs refactor

### LINKED ISSUE #552: Refactor crawl.js
Crawl.js is the script which controls the buttons on the dashboard. Right now the code is very difficult to make changes or add features to, and somewhat unstable.

### PR DESCRIPTION
**Pull request by brittainhard**
closes #552

### CODE REVIEW

**Comment by ahmadia** [comment]
RTM?

**Comment by chrismattmann** [comment]
+1 merge

**Comment by ahmadia** [comment]
Thanks @brittainhard and @chrismattmann for review.

**Comment by chrismattmann** [comment]
Thanks @ahmadia

**Comment by chrismattmann** [comment]
Thanks @brittainhard

**Pull request merged**
