### PR TITLE
Add glossary

### PR DESCRIPTION
**Pull request by ahmadia**

### CODE REVIEW

**Comment by ahmadia** [comment]
@brittainhard / @amfarrell - Looks like we've got a failing test in master.  Is this a known issue or should I raise one?

**Comment by brittainhard** [comment]
@ahmadia the test is a failing selenium test. They have a habit of breaking travis every once in a while. One of the PRs that got merged had a selenium test as a failing test. It's useful to have an issue about this, so we can figure out what is happening. I'll probably start recording the errors there.

Nothing to worry about though.

**Comment by ahmadia** [comment]
I'm on it.

**Comment by ahmadia** [comment]
https://github.com/memex-explorer/memex-explorer/issues/502

**Pull request merged**
