### PR TITLE
Amfarrell/create stack idempotent

### PR DESCRIPTION
**Pull request by amfarrell**

### CODE REVIEW

**Comment by ahmadia** [comment]
Let's remove the line in the salt configuration that deletes the database, then try and reprovision to test.

**Comment by ahmadia** [comment]
I'm just going to cherry-pick 5008b8b and reset this branch.

**Comment by amfarrell** [comment]
👍

**Comment by ahmadia** [comment]
Cherry-picked.

**Comment by ahmadia** [comment]
Thanks @amfarrell.  Have a safe flight back to Austin!

**Pull request merged**
