### PR TITLE
First pass at Salt/Vagrantfile configuration

### PR DESCRIPTION
**Pull request by ahmadia**
This supercedes the current Vagrantfile and fixes a bunch of bugs.  I'm still ironing it out, but feel free to give it a go if you've got spare bandwidth.

### CODE REVIEW

**Comment by ahmadia** [comment]
I'm shamelessly merging this into master.  The only dangerous piece in here is I've added `docker-compose` as an installation to environment.yml.  This should have gone into a separate commit.  The rest of the files touched are directly under Vagrant/Salt.

**Comment by ahmadia** [comment]
@amfarrell - This needs your review (I know, I've already merged it :)

Test by blowing away your current vagrant box with:

```
vagrant destroy
```

Then bring it up with:

```
time vagrant up
```

I put the time command in there because I want to know how long this takes to execute on a typical developer laptop :)

It should get all the way through to launching memex-explorer.  If that succeeds, poke around and see what's working.  I think you mentioned that there's a hardcode in the way Kibana is being launched/detected, and that we need to fix this.  If you've got notes on this, please raise an issue or fix.  Thanks!

**Comment by ahmadia** [comment]
Caveats: this wipes away the database on reprovision instead of migration.  Also, this takes about 45 minutes to provision on my laptop at home network speeds.

**Comment by amfarrell** [comment]
The hardcode isn't in the way kibana is being launched/detected, just in the way it is listed as a Service (the model is still named App)

**Pull request merged**
