### PR TITLE
Fix Issue with Deleting Project Erroring

### LINKED ISSUE #738: Cannot delete some instances of model CrawlModel
Encountered after trying to delete a project that contains references to crawlmodels used by another project.

Brittain, this seems like an internal error that we're triggering from the way we've structured our models.  What do you think?

```
Environment:


Request Method: POST
Request URL: http://localhost:8000/projects/wikipedia-crawl-with-nutch/settings/delete/

Django Version: 1.7.3
Python Version: 2.7.8
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'crispy_forms',
 'base',
 'task_manager',
 'rest_framework',
 'apps.crawl_space',
 'debug_toolbar')
Installed Middleware:
(u'debug_toolbar.middleware.DebugToolbarMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware')


Traceback:
File "/Users/aahmadia/anaconda/envs/memex/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/Users/aahmadia/anaconda/envs/memex/lib/python2.7/site-packages/django/views/generic/base.py" in view
  69.             return self.dispatch(request, *args, **kwargs)
File "/Users/aahmadia/anaconda/envs/memex/lib/python2.7/site-packages/django/views/generic/base.py" in dispatch
  87.         return handler(request, *args, **kwargs)
File "/Users/aahmadia/anaconda/envs/memex/lib/python2.7/site-packages/django/views/generic/edit.py" in post
  259.         return self.delete(request, *args, **kwargs)
File "/Users/aahmadia/memex-explorer/source/base/views.py" in delete
  153.         return super(DeleteProjectView, self).delete(request, *args, **kwargs)
File "/Users/aahmadia/anaconda/envs/memex/lib/python2.7/site-packages/django/views/generic/edit.py" in delete
  254.         self.object.delete()
File "/Users/aahmadia/anaconda/envs/memex/lib/python2.7/site-packages/django/db/models/base.py" in delete
  738.         collector.collect([self])
File "/Users/aahmadia/anaconda/envs/memex/lib/python2.7/site-packages/django/db/models/deletion.py" in collect
  199.                     field.rel.on_delete(self, field, sub_objs, self.using)
File "/Users/aahmadia/anaconda/envs/memex/lib/python2.7/site-packages/django/db/models/deletion.py" in CASCADE
  17.                       source_attr=field.name, nullable=field.null)
File "/Users/aahmadia/anaconda/envs/memex/lib/python2.7/site-packages/django/db/models/deletion.py" in collect
  199.                     field.rel.on_delete(self, field, sub_objs, self.using)
File "/Users/aahmadia/anaconda/envs/memex/lib/python2.7/site-packages/django/db/models/deletion.py" in PROTECT
  27.         sub_objs

Exception Type: ProtectedError at /projects/wikipedia-crawl-with-nutch/settings/delete/
Exception Value: ("Cannot delete some instances of model 'CrawlModel' because they are referenced through a protected foreign key: 'Crawl.crawl_model'", [<Crawl: c11>])
```

```
ProtectedError at /projects/wikipedia-crawl-with-nutch/settings/delete/
("Cannot delete some instances of model 'CrawlModel' because they are referenced through a protected foreign key: 'Crawl.crawl_model'", [<Crawl: c11>])
Request Method:	POST
Request URL:	http://localhost:8000/projects/wikipedia-crawl-with-nutch/settings/delete/
Django Version:	1.7.3
Exception Type:	ProtectedError
Exception Value:	
("Cannot delete some instances of model 'CrawlModel' because they are referenced through a protected foreign key: 'Crawl.crawl_model'", [<Crawl: c11>])
Exception Location:	/Users/aahmadia/anaconda/envs/memex/lib/python2.7/site-packages/django/db/models/deletion.py in PROTECT, line 27
Python Executable:	/Users/aahmadia/anaconda/envs/memex/bin/python
Python Version:	2.7.8
Python Path:	
['/Users/aahmadia/memex-explorer/source',
 '/Users/aahmadia/memex-explorer/source',
 '/Users/aahmadia/memex-explorer/source',
 '/Users/aahmadia/nutch/nutch-python',
 '/Users/aahmadia/anaconda/envs/memex/lib/python27.zip',
 '/Users/aahmadia/anaconda/envs/memex/lib/python2.7',
 '/Users/aahmadia/anaconda/envs/memex/lib/python2.7/plat-darwin',
 '/Users/aahmadia/anaconda/envs/memex/lib/python2.7/plat-mac',
 '/Users/aahmadia/anaconda/envs/memex/lib/python2.7/plat-mac/lib-scriptpackages',
 '/Users/aahmadia/anaconda/envs/memex/lib/python2.7/lib-tk',
 '/Users/aahmadia/anaconda/envs/memex/lib/python2.7/lib-old',
 '/Users/aahmadia/anaconda/envs/memex/lib/python2.7/lib-dynload',
 '/Users/aahmadia/anaconda/envs/memex/lib/python2.7/site-packages/Sphinx-1.2.3-py2.7.egg',
 '/Users/aahmadia/anaconda/envs/memex/lib/python2.7/site-packages/gunicorn-19.1.0-py2.7.egg',
 '/Users/aahmadia/anaconda/envs/memex/lib/python2.7/site-packages/pytest_runner-2.6.2-py2.7.egg',
 '/Users/aahmadia/anaconda/envs/memex/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg',
 '/Users/aahmadia/anaconda/envs/memex/lib/python2.7/site-packages',
 '/Users/aahmadia/anaconda/envs/memex/lib/python2.7/site-packages/elasticsearch-1.6.0-py2.7.egg',
 '/Users/aahmadia/anaconda/envs/memex/lib/python2.7/site-packages/nutch-1.10.3-py2.7.egg',
 '/Users/aahmadia/anaconda/envs/memex/lib/python2.7/site-packages/urllib3-1.11-py2.7.egg',
 '/Users/aahmadia/memex-explorer/source']
Server time:	Wed, 28 Oct 2015 15:21:17 +0000
```

### PR DESCRIPTION
**Pull request by brittainhard**
closes #738

### CODE REVIEW

**Comment by brittainhard** [comment]
Basically, what's happening here is that crawl models are getting deleted, but since they are protected from a cascading delete, it throws when you delete a project. I added some code to delete the crawls first, before the models are deleted.

@ahmadia will you take a look?

**Comment by ahmadia** [comment]
Yeah I think I know how to yes this.

On Monday, November 2, 2015, Brittain Hard <notifications@github.com> wrote:

> Basically, what's happening here is that crawl models are getting deleted,
> but since they are protected from a cascading delete, it throws when you
> delete a project. I added some code to delete the crawls first, before the
> models are deleted.
>
> @ahmadia <https://github.com/ahmadia> will you take a look?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/memex-explorer/memex-explorer/pull/749#issuecomment-153101048>
> .
>


-- 
_______________________________

Aron Ahmadia
Computational and Data Scientist

[image: Continuum Analytics] <http://continuum.io>

**Comment by brittainhard** [comment]
You know how to say yes but you're not saying yes? :D

**Comment by ahmadia** [comment]
iPhone keyboard I meant test. I will "yes" this after I test it :)

On Monday, November 2, 2015, Brittain Hard <notifications@github.com> wrote:

> You know how to say yes but you're not saying yes? :D
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/memex-explorer/memex-explorer/pull/749#issuecomment-153104311>
> .
>


-- 
_______________________________

Aron Ahmadia
Computational and Data Scientist

[image: Continuum Analytics] <http://continuum.io>

**Comment by ahmadia** [comment]
looks good.

**Pull request merged**
